markdown: kramdown
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
title: haidaoxiaofei's Blog
description: haidaoxiaofei's Blog, powered by Jekyll...
feed: http://haidaoxiaofei.github.io/atom.xml

author: haidaoxiaofei

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
